<template>
  <div class="text-sm text-gray-900 h-full">
    <div class="px-10 py-10 h-full w-full bg-gray-100 rounded-3xl opacity-40">
      <div class="rounded-3xl bg-gray-300">
        <div class="px-8 py-8 overflow-auto max-h-[90vh]">
          <table class="border">
            <tr v-for="word in data" class="h-10 w-[100%]">
              <td class="w-memory">{{ word.word }}</td>
              <td class="w-memory">{{ word.meaning }}</td>
              <td class="w-memory">{{ word.pronounciation }}</td>
              <td class="w-memory text-center"><MemoryAxis :process="word.spellProcess" :num="9"/></td>
              <td class="w-memory text-center"><MemoryAxis :process="word.translateProcess" :num="9"/></td>
            </tr>
          </table>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup>
import { ref } from 'vue';
import MemoryAxis from '../components/MemoryAxis.vue'

const data = ref([
{
    word: "compatibility",
    meaning: "n.兼容性",
    pronounciation: "[]",
    spellProcess: 3,
    translateProcess: 5,
  },
  {
    word: "compatibility",
    meaning: "n.兼容性",
    pronounciation: "[]",
    spellProcess: 3,
    translateProcess: 5,
  },
  {
    word: "compatibility",
    meaning: "n.兼容性",
    pronounciation: "[]",
    spellProcess: 3,
    translateProcess: 5,
  },
  {
    word: "compatibility",
    meaning: "n.兼容性",
    pronounciation: "[]",
    spellProcess: 3,
    translateProcess: 5,
  },
  {
    word: "compatibility",
    meaning: "n.兼容性",
    pronounciation: "[]",
    spellProcess: 3,
    translateProcess: 5,
  },
  {
    word: "compatibility",
    meaning: "n.兼容性",
    pronounciation: "[]",
    spellProcess: 3,
    translateProcess: 5,
  },
  {
    word: "compatibility",
    meaning: "n.兼容性",
    pronounciation: "[]",
    spellProcess: 3,
    translateProcess: 5,
  },
  {
    word: "compatibility",
    meaning: "n.兼容性",
    pronounciation: "[]",
    spellProcess: 3,
    translateProcess: 5,
  },
  {
    word: "compatibility",
    meaning: "n.兼容性",
    pronounciation: "[]",
    spellProcess: 3,
    translateProcess: 5,
  },
  {
    word: "compatibility",
    meaning: "n.兼容性",
    pronounciation: "[]",
    spellProcess: 3,
    translateProcess: 5,
  },
  {
    word: "compatibility",
    meaning: "n.兼容性",
    pronounciation: "[]",
    spellProcess: 3,
    translateProcess: 5,
  },
  {
    word: "compatibility",
    meaning: "n.兼容性",
    pronounciation: "[]",
    spellProcess: 3,
    translateProcess: 5,
  },
  {
    word: "compatibility",
    meaning: "n.兼容性",
    pronounciation: "[]",
    spellProcess: 3,
    translateProcess: 5,
  },
  {
    word: "compatibility",
    meaning: "n.兼容性",
    pronounciation: "[]",
    spellProcess: 3,
    translateProcess: 5,
  },
  {
    word: "compatibility",
    meaning: "n.兼容性",
    pronounciation: "[]",
    spellProcess: 3,
    translateProcess: 5,
  },
  {
    word: "compatibility",
    meaning: "n.兼容性",
    pronounciation: "[]",
    spellProcess: 3,
    translateProcess: 5,
  },
  {
    word: "compatibility",
    meaning: "n.兼容性",
    pronounciation: "[]",
    spellProcess: 3,
    translateProcess: 5,
  },
  {
    word: "compatibility",
    meaning: "n.兼容性",
    pronounciation: "[]",
    spellProcess: 3,
    translateProcess: 5,
  },
  {
    word: "compatibility",
    meaning: "n.兼容性",
    pronounciation: "[]",
    spellProcess: 3,
    translateProcess: 5,
  },
  {
    word: "compatibility",
    meaning: "n.兼容性",
    pronounciation: "[]",
    spellProcess: 3,
    translateProcess: 5,
  },
  {
    word: "compatibility",
    meaning: "n.兼容性",
    pronounciation: "[]",
    spellProcess: 3,
    translateProcess: 5,
  },
  {
    word: "compatibility",
    meaning: "n.兼容性",
    pronounciation: "[]",
    spellProcess: 3,
    translateProcess: 5,
  },
  {
    word: "compatibility",
    meaning: "n.兼容性",
    pronounciation: "[]",
    spellProcess: 3,
    translateProcess: 5,
  },
  {
    word: "compatibility",
    meaning: "n.兼容性",
    pronounciation: "[]",
    spellProcess: 3,
    translateProcess: 5,
  },
  {
    word: "compatibility",
    meaning: "n.兼容性",
    pronounciation: "[]",
    spellProcess: 3,
    translateProcess: 5,
  },
  {
    word: "compatibility",
    meaning: "n.兼容性",
    pronounciation: "[]",
    spellProcess: 3,
    translateProcess: 5,
  },
  {
    word: "compatibility",
    meaning: "n.兼容性",
    pronounciation: "[]",
    spellProcess: 3,
    translateProcess: 5,
  },
  {
    word: "compatibility",
    meaning: "n.兼容性",
    pronounciation: "[]",
    spellProcess: 3,
    translateProcess: 5,
  },
  {
    word: "compatibility",
    meaning: "n.兼容性",
    pronounciation: "[]",
    spellProcess: 3,
    translateProcess: 5,
  },
  {
    word: "compatibility",
    meaning: "n.兼容性",
    pronounciation: "[]",
    spellProcess: 3,
    translateProcess: 5,
  },
  {
    word: "compatibility",
    meaning: "n.兼容性",
    pronounciation: "[]",
    spellProcess: 3,
    translateProcess: 5,
  },
  {
    word: "compatibility",
    meaning: "n.兼容性",
    pronounciation: "[]",
    spellProcess: 3,
    translateProcess: 5,
  },
  {
    word: "compatibility",
    meaning: "n.兼容性",
    pronounciation: "[]",
    spellProcess: 3,
    translateProcess: 5,
  },
  {
    word: "compatibility",
    meaning: "n.兼容性",
    pronounciation: "[]",
    spellProcess: 3,
    translateProcess: 5,
  },
  {
    word: "compatibility",
    meaning: "n.兼容性",
    pronounciation: "[]",
    spellProcess: 3,
    translateProcess: 5,
  },
  {
    word: "compatibility",
    meaning: "n.兼容性",
    pronounciation: "[]",
    spellProcess: 3,
    translateProcess: 5,
  },
  {
    word: "compatibility",
    meaning: "n.兼容性",
    pronounciation: "[]",
    spellProcess: 3,
    translateProcess: 5,
  },
  {
    word: "compatibility",
    meaning: "n.兼容性",
    pronounciation: "[]",
    spellProcess: 3,
    translateProcess: 5,
  },
  {
    word: "compatibility",
    meaning: "n.兼容性",
    pronounciation: "[]",
    spellProcess: 3,
    translateProcess: 5,
  },
  {
    word: "compatibility",
    meaning: "n.兼容性",
    pronounciation: "[]",
    spellProcess: 3,
    translateProcess: 5,
  },
  {
    word: "compatibility",
    meaning: "n.兼容性",
    pronounciation: "[]",
    spellProcess: 3,
    translateProcess: 5,
  },
  {
    word: "compatibility",
    meaning: "n.兼容性",
    pronounciation: "[]",
    spellProcess: 3,
    translateProcess: 5,
  },
  {
    word: "compatibility",
    meaning: "n.兼容性",
    pronounciation: "[]",
    spellProcess: 3,
    translateProcess: 5,
  },
  {
    word: "compatibility",
    meaning: "n.兼容性",
    pronounciation: "[]",
    spellProcess: 3,
    translateProcess: 5,
  },
{
    word: "compatibility",
    meaning: "n.兼容性",
    pronounciation: "[]",
    spellProcess: 3,
    translateProcess: 5,
  },
  {
    word: "compatibility",
    meaning: "n.兼容性",
    pronounciation: "[]",
    spellProcess: 3,
    translateProcess: 5,
  },
  {
    word: "compatibility",
    meaning: "n.兼容性",
    pronounciation: "[]",
    spellProcess: 3,
    translateProcess: 5,
  },
  {
    word: "compatibility",
    meaning: "n.兼容性",
    pronounciation: "[]",
    spellProcess: 3,
    translateProcess: 5,
  },
  {
    word: "compatibility",
    meaning: "n.兼容性",
    pronounciation: "[]",
    spellProcess: 3,
    translateProcess: 5,
  },
  {
    word: "compatibility",
    meaning: "n.兼容性",
    pronounciation: "[]",
    spellProcess: 3,
    translateProcess: 5,
  },
  {
    word: "compatibility",
    meaning: "n.兼容性",
    pronounciation: "[]",
    spellProcess: 3,
    translateProcess: 5,
  },
  {
    word: "compatibility",
    meaning: "n.兼容性",
    pronounciation: "[]",
    spellProcess: 3,
    translateProcess: 5,
  },
  {
    word: "compatibility",
    meaning: "n.兼容性",
    pronounciation: "[]",
    spellProcess: 3,
    translateProcess: 5,
  },
  {
    word: "compatibility",
    meaning: "n.兼容性",
    pronounciation: "[]",
    spellProcess: 3,
    translateProcess: 5,
  },
  {
    word: "compatibility",
    meaning: "n.兼容性",
    pronounciation: "[]",
    spellProcess: 3,
    translateProcess: 5,
  },
  {
    word: "compatibility",
    meaning: "n.兼容性",
    pronounciation: "[]",
    spellProcess: 3,
    translateProcess: 5,
  },
  {
    word: "compatibility",
    meaning: "n.兼容性",
    pronounciation: "[]",
    spellProcess: 3,
    translateProcess: 5,
  },
  {
    word: "compatibility",
    meaning: "n.兼容性",
    pronounciation: "[]",
    spellProcess: 3,
    translateProcess: 5,
  },
  {
    word: "compatibility",
    meaning: "n.兼容性",
    pronounciation: "[]",
    spellProcess: 3,
    translateProcess: 5,
  },
  {
    word: "compatibility",
    meaning: "n.兼容性",
    pronounciation: "[]",
    spellProcess: 3,
    translateProcess: 5,
  },
  {
    word: "compatibility",
    meaning: "n.兼容性",
    pronounciation: "[]",
    spellProcess: 3,
    translateProcess: 5,
  },
  {
    word: "compatibility",
    meaning: "n.兼容性",
    pronounciation: "[]",
    spellProcess: 3,
    translateProcess: 5,
  },
  {
    word: "compatibility",
    meaning: "n.兼容性",
    pronounciation: "[]",
    spellProcess: 3,
    translateProcess: 5,
  },
  {
    word: "compatibility",
    meaning: "n.兼容性",
    pronounciation: "[]",
    spellProcess: 3,
    translateProcess: 5,
  },
{
    word: "compatibility",
    meaning: "n.兼容性",
    pronounciation: "[]",
    spellProcess: 3,
    translateProcess: 5,
  },
  {
    word: "compatibility",
    meaning: "n.兼容性",
    pronounciation: "[]",
    spellProcess: 3,
    translateProcess: 5,
  },
  {
    word: "compatibility",
    meaning: "n.兼容性",
    pronounciation: "[]",
    spellProcess: 3,
    translateProcess: 5,
  },
  {
    word: "compatibility",
    meaning: "n.兼容性",
    pronounciation: "[]",
    spellProcess: 3,
    translateProcess: 5,
  },
  {
    word: "compatibility",
    meaning: "n.兼容性",
    pronounciation: "[]",
    spellProcess: 3,
    translateProcess: 5,
  },
  {
    word: "compatibility",
    meaning: "n.兼容性",
    pronounciation: "[]",
    spellProcess: 3,
    translateProcess: 5,
  },
  {
    word: "compatibility",
    meaning: "n.兼容性",
    pronounciation: "[]",
    spellProcess: 3,
    translateProcess: 5,
  },
  {
    word: "compatibility",
    meaning: "n.兼容性",
    pronounciation: "[]",
    spellProcess: 4,
    translateProcess: 5,
  },
])
</script>